name: Deploy on server
on:
  workflow_run:
      workflows: [python-package]
      branches: [main]
      types:
        - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    steps:
    - run: poetry publish --build
